title: Sandeep Dasgupta's Blog 
author: GitHub User
email: sdasgup3@illinois.edu
description: > # this means to ignore newlines until "baseurl:"
  A Blog to collect and express my thoughs on various topics.
baseurl: ''
github_username:  sdasgup3


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-compose

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
